services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: star-chasing-merchant
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
